### ISSUE TITLE
Query selectors outdated

### ISSUE THREAD

**Issue by mmoraiz** [0ssamaak0/Super-Bing#1]
First of all thanks for the script! 

However the query selectors are outdated, I changed them to the following ones and it continues to work, in case you want to update them :).

`var searchBox = document.querySelector("#b_sydConvCont > cib-serp").shadowRoot.querySelector("#cib-action-bar-main").shadowRoot.querySelector("div > div.main-container > div > div.input-row > cib-text-input").shadowRoot.querySelector("#searchbox");`

`var letterCounter = document.querySelector("#b_sydConvCont > cib-serp").shadowRoot.querySelector("#cib-action-bar-main").shadowRoot.querySelector("div > div.main-container > div > div.bottom-controls > div.bottom-right-controls > div.letter-counter").childNodes[3];`

**Comment by 0ssamaak0** [comment]
Thank you! Can you make a pull request with this new query?

**Comment by 0ssamaak0** [comment]
it worked, thank you very much
